name: NodeJS with Webpack

on:
  push:
    tags:
      - 'v*'
    # branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [linux, macos, windows]
        node-version: [18]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 18
        
    - name: Build
      run: |
        npm install
        
    - name: pkg
      run: |
        # npm run build
        #每个${{matrix.target}}版本执行一次
        npx pkg -t ${{matrix.target}} .
        mv "$(ls dist/*)" "$(ls dist/* | sed 's/gitflow-test/test-${{matrix.target}}-${{ github.ref_name }}/g')"
        echo "ASSET_NAME=$(ls dist)" >> $GITHUB_ENV
      
    - name: Publishing to GitHub Artifacts
      uses: actions/upload-artifact@v4
      if: github.event_name != 'release'
      with:
          name: ${{ env.ASSET_NAME }}
          path: dist/*

    - name: Publishing to GitHub Releases
      uses: svenstaro/upload-release-action@2.9.0
      if: github.event_name == 'release'
      with:
        repo_token: ${{ github.token }}
        file: dist/*
        tag: ${{ github.ref }}
        file_glob: true
