name: NodeJS with Webpack

on:
  push:
    tags:
      - 'v*'
    # branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        
    - name: pkg
      run: npm run build
      
    - name: Publishing to GitHub Artifacts
      uses: actions/upload-artifact@v4
      if: github.event_name != 'release'
      with:
          name: ${{ env.ASSET_NAME }}
          path: dist/*

    - name: Publishing to GitHub Releases
      uses: svenstaro/upload-release-action@2.9.0
      if: github.event_name == 'release'
      with:
        repo_token: ${{ github.token }}
        file: dist/*
        tag: ${{ github.ref }}
        file_glob: true
